export const SEO_SERVICES = [
    { slug: 'whatsapp', name: 'WhatsApp' },
    { slug: 'telegram', name: 'Telegram' },
    { slug: 'tinder', name: 'Tinder' },
    { slug: 'google', name: 'Google / Gmail' },
    { slug: 'facebook', name: 'Facebook' },
    { slug: 'instagram', name: 'Instagram' },
    { slug: 'tiktok', name: 'TikTok' },
    { slug: 'uber', name: 'Uber' },
    { slug: 'openai', name: 'OpenAI / ChatGPT' },
    { slug: 'discord', name: 'Discord' },
    { slug: 'twitter', name: 'Twitter / X' },
    { slug: 'amazon', name: 'Amazon' },
    { slug: 'paypal', name: 'PayPal' },
    { slug: 'bumble', name: 'Bumble' },
    { slug: 'hinge', name: 'Hinge' },
    { slug: 'grindr', name: 'Grindr' },
    { slug: 'signal', name: 'Signal' },
    { slug: 'snapchat', name: 'Snapchat' },
    { slug: 'venmo', name: 'Venmo' },
    { slug: 'kakao', name: 'KakaoTalk' },
    { slug: 'microsoft', name: 'Microsoft / Outlook' },
    { slug: 'apple', name: 'Apple / iCloud' },
    { slug: 'linkedin', name: 'LinkedIn' },
    { slug: 'reddit', name: 'Reddit' },
    { slug: 'pinterest', name: 'Pinterest' },
    { slug: 'etsy', name: 'Etsy' },
    { slug: 'airbnb', name: 'Airbnb' },
    { slug: 'revolut', name: 'Revolut' },
    { slug: 'wise', name: 'Wise' },
    { slug: 'binance', name: 'Binance' },
    { slug: 'coinbase', name: 'Coinbase' },
    { slug: 'crypto-com', name: 'Crypto.com' },
    { slug: 'steam', name: 'Steam' },
    { slug: 'twitch', name: 'Twitch' },
    { slug: 'epic-games', name: 'Epic Games' },
    { slug: 'riot-games', name: 'Riot Games' },
];

export const SEO_COUNTRIES = [
    'US', 'GB', 'CA', 'DE', 'NL', 'FR', 'ES', 'IT', 'AU', 'BR',
    'IN', 'ID', 'PH', 'TH', 'VN', 'MY', 'PL', 'SE', 'IE', 'AT',
    'CH', 'BE', 'NO', 'DK', 'FI', 'TR', 'ZA', 'NG', 'MX', 'CO'
];
