export interface Service {
    id: string;
    name: string;
    price: number;
    category: string;
}

export const MOCK_SERVICES: Service[] = [
    // Custom
    { id: 'custom', name: 'Other Service (Not Listed)', price: 0.60, category: 'Other' },

    // --- Social Media (50+) ---
    { id: 'tinder', name: 'Tinder', price: 0.69, category: 'Social' },
    { id: 'facebook', name: 'Facebook', price: 1.15, category: 'Social' },
    { id: 'instagram', name: 'Instagram', price: 0.85, category: 'Social' },
    { id: 'twitter', name: 'X (Twitter)', price: 0.60, category: 'Social' },
    { id: 'tiktok', name: 'TikTok', price: 0.60, category: 'Social' },
    { id: 'snapchat', name: 'Snapchat', price: 0.57, category: 'Social' },
    { id: 'linkedin', name: 'LinkedIn', price: 0.57, category: 'Social' },
    { id: 'bumble', name: 'Bumble', price: 0.61, category: 'Social' },
    { id: 'hinge', name: 'Hinge', price: 0.59, category: 'Social' },
    { id: 'grindr', name: 'Grindr', price: 0.57, category: 'Social' },
    { id: 'badoo', name: 'Badoo', price: 0.57, category: 'Social' },
    { id: 'okcupid', name: 'OkCupid', price: 0.55, category: 'Social' },
    { id: 'pof', name: 'Plenty of Fish', price: 0.45, category: 'Social' },
    { id: 'reddit', name: 'Reddit', price: 0.68, category: 'Social' },
    { id: 'discord', name: 'Discord', price: 0.50, category: 'Social' },
    { id: 'clubhouse', name: 'Clubhouse', price: 0.57, category: 'Social' },
    { id: 'pinterest', name: 'Pinterest', price: 0.57, category: 'Social' },
    { id: 'tumblr', name: 'Tumblr', price: 0.30, category: 'Social' },
    { id: 'twitch', name: 'Twitch', price: 0.57, category: 'Social' },
    { id: 'vkontakte', name: 'VK', price: 0.85, category: 'Social' },
    { id: 'weibo', name: 'Weibo', price: 0.57, category: 'Social' },
    { id: 'xing', name: 'Xing', price: 0.40, category: 'Social' },
    { id: 'nextdoor', name: 'Nextdoor', price: 0.57, category: 'Social' },
    { id: 'meetup', name: 'Meetup', price: 0.57, category: 'Social' },
    { id: 'tagged', name: 'Tagged', price: 0.57, category: 'Social' },
    { id: 'lovoo', name: 'Lovoo', price: 0.60, category: 'Social' },
    { id: 'skout', name: 'Skout', price: 0.57, category: 'Social' },
    { id: 'yubo', name: 'Yubo', price: 0.55, category: 'Social' },
    { id: 'patreon', name: 'Patreon', price: 0.50, category: 'Social' },
    { id: 'onlyfans', name: 'OnlyFans', price: 0.57, category: 'Social' },
    { id: 'fansly', name: 'Fansly', price: 0.60, category: 'Social' },
    { id: 'mewe', name: 'MeWe', price: 0.57, category: 'Social' },
    { id: 'parler', name: 'Parler', price: 0.57, category: 'Social' },
    { id: 'gab', name: 'Gab', price: 0.60, category: 'Social' },
    { id: 'rumble', name: 'Rumble', price: 0.57, category: 'Social' },
    { id: 'truth_social', name: 'Truth Social', price: 0.50, category: 'Social' },
    { id: 'gettr', name: 'Gettr', price: 0.45, category: 'Social' },
    { id: 'mastodon', name: 'Mastodon', price: 0.35, category: 'Social' },
    { id: 'amino', name: 'Amino', price: 0.40, category: 'Social' },
    { id: 'band', name: 'Band', price: 0.40, category: 'Social' },
    { id: 'plurk', name: 'Plurk', price: 0.35, category: 'Social' },
    { id: 'livejournal', name: 'LiveJournal', price: 0.30, category: 'Social' },
    { id: 'myspace', name: 'MySpace', price: 0.57, category: 'Social' },
    { id: 'flickr', name: 'Flickr', price: 0.60, category: 'Social' },
    { id: 'periscope', name: 'Periscope', price: 0.57, category: 'Social' },
    { id: 'tango', name: 'Tango', price: 0.60, category: 'Social' },
    { id: 'bigo', name: 'Bigo Live', price: 0.50, category: 'Social' },
    { id: 'likee', name: 'Likee', price: 0.57, category: 'Social' },
    { id: 'askfm', name: 'Ask.fm', price: 0.60, category: 'Social' },
    { id: 'zalo', name: 'Zalo', price: 0.57, category: 'Social' },

    // --- Messaging (50+) ---
    { id: 'telegram', name: 'Telegram', price: 1.51, category: 'Messaging' },
    { id: 'whatsapp', name: 'WhatsApp', price: 1.87, category: 'Messaging' },
    { id: 'viber', name: 'Viber', price: 0.53, category: 'Messaging' },
    { id: 'signal', name: 'Signal', price: 0.57, category: 'Messaging' },
    { id: 'line', name: 'LINE', price: 0.57, category: 'Messaging' },
    { id: 'wechat', name: 'WeChat', price: 0.57, category: 'Messaging' },
    { id: 'kakaotalk', name: 'KakaoTalk', price: 0.51, category: 'Messaging' },
    { id: 'imo', name: 'Imo', price: 0.57, category: 'Messaging' },
    { id: 'messenger', name: 'Messenger', price: 0.60, category: 'Messaging' },
    { id: 'threema', name: 'Threema', price: 0.50, category: 'Messaging' },
    { id: 'wire', name: 'Wire', price: 0.70, category: 'Messaging' },
    { id: 'wickr', name: 'Wickr', price: 0.57, category: 'Messaging' },
    { id: 'session', name: 'Session', price: 0.45, category: 'Messaging' },
    { id: 'botim', name: 'Botim', price: 0.40, category: 'Messaging' },
    { id: 'totok', name: 'ToTok', price: 0.40, category: 'Messaging' },
    { id: 'hike', name: 'Hike', price: 0.60, category: 'Messaging' },
    { id: 'groupme', name: 'GroupMe', price: 0.57, category: 'Messaging' },
    { id: 'voxer', name: 'Voxer', price: 0.40, category: 'Messaging' },
    { id: 'marco_polo', name: 'Marco Polo', price: 0.40, category: 'Messaging' },
    { id: 'tox', name: 'Tox', price: 0.35, category: 'Messaging' },
    { id: 'element', name: 'Element', price: 0.40, category: 'Messaging' },
    { id: 'matrix', name: 'Matrix', price: 0.40, category: 'Messaging' },
    { id: 'xmpp', name: 'XMPP', price: 0.60, category: 'Messaging' },
    { id: 'icq', name: 'ICQ', price: 0.57, category: 'Messaging' },
    { id: 'qq', name: 'QQ', price: 0.50, category: 'Messaging' },
    { id: 'yy', name: 'YY', price: 0.45, category: 'Messaging' },
    { id: 'momo', name: 'Momo', price: 0.45, category: 'Messaging' },
    { id: 'tan_tan', name: 'Tantan', price: 0.50, category: 'Messaging' },
    { id: 'dingtalk', name: 'DingTalk', price: 0.55, category: 'Messaging' },
    { id: 'lark', name: 'Lark', price: 0.50, category: 'Messaging' },
    { id: 'slack', name: 'Slack', price: 0.50, category: 'Messaging' },
    { id: 'teams', name: 'Microsoft Teams', price: 0.50, category: 'Messaging' },
    { id: 'zoom', name: 'Zoom', price: 0.60, category: 'Messaging' },
    { id: 'skype', name: 'Skype', price: 0.57, category: 'Messaging' },
    { id: 'google_voice', name: 'Google Voice', price: 0.60, category: 'Messaging' },
    { id: 'textnow', name: 'TextNow', price: 0.50, category: 'Messaging' },
    { id: 'burner', name: 'Burner', price: 0.55, category: 'Messaging' },
    { id: 'hushed', name: 'Hushed', price: 0.55, category: 'Messaging' },
    { id: 'sideline', name: 'Sideline', price: 0.60, category: 'Messaging' },
    { id: 'line2', name: 'Line2', price: 0.57, category: 'Messaging' },
    { id: 'grasshopper', name: 'Grasshopper', price: 0.57, category: 'Messaging' },
    { id: 'openphone', name: 'OpenPhone', price: 0.60, category: 'Messaging' },

    // --- Finance & Crypto (NOT SUPPORTED by SMSPool Rentals) ---
    // Section removed to prevent errors as per SMSPool policy against financial services on rentals.

    // --- Shopping & Ecommerce (50+) ---
    { id: 'amazon', name: 'Amazon', price: 0.85, category: 'Shopping' },
    { id: 'ebay', name: 'eBay', price: 0.77, category: 'Shopping' },
    { id: 'etsy', name: 'Etsy', price: 0.57, category: 'Shopping' },
    { id: 'temu', name: 'Temu', price: 0.57, category: 'Shopping' },
    { id: 'shein', name: 'Shein', price: 0.93, category: 'Shopping' },
    { id: 'walmart', name: 'Walmart', price: 0.81, category: 'Shopping' },
    { id: 'target', name: 'Target', price: 0.57, category: 'Shopping' },
    { id: 'bestbuy', name: 'Best Buy', price: 0.68, category: 'Shopping' },
    { id: 'costco', name: 'Costco', price: 0.60, category: 'Shopping' },
    { id: 'nike', name: 'Nike', price: 0.57, category: 'Shopping' },
    { id: 'adidas', name: 'Adidas', price: 0.57, category: 'Shopping' },
    { id: 'aliexpress', name: 'AliExpress', price: 0.76, category: 'Shopping' },
    { id: 'lazada', name: 'Lazada', price: 0.57, category: 'Shopping' },
    { id: 'shopee', name: 'Shopee', price: 0.57, category: 'Shopping' },
    { id: 'wish', name: 'Wish', price: 0.57, category: 'Shopping' },
    { id: 'alibaba', name: 'Alibaba', price: 0.57, category: 'Shopping' },
    { id: 'taobao', name: 'Taobao', price: 0.40, category: 'Shopping' },
    { id: 'tmall', name: 'Tmall', price: 0.45, category: 'Shopping' },
    { id: 'jd_com', name: 'JD.com', price: 0.45, category: 'Shopping' },
    { id: 'rakuten_shop', name: 'Rakuten Ichiba', price: 0.45, category: 'Shopping' },
    { id: 'mercari', name: 'Mercari', price: 0.40, category: 'Shopping' },
    // Removed duplicate poshmark, depop
    { id: 'vinted', name: 'Vinted', price: 0.57, category: 'Shopping' },
    { id: 'poshmark', name: 'Poshmark', price: 0.57, category: 'Shopping' },
    { id: 'depop', name: 'Depop', price: 0.57, category: 'Shopping' },
    { id: 'mercari', name: 'Mercari', price: 0.57, category: 'Shopping' },
    { id: 'offerup', name: 'OfferUp', price: 0.57, category: 'Shopping' },
    { id: 'carousell', name: 'Carousell', price: 0.57, category: 'Shopping' },
    { id: 'craigslist', name: 'Craigslist', price: 0.57, category: 'Shopping' },
    { id: 'zara', name: 'Zara', price: 1.13, category: 'Shopping' },
    { id: 'hm', name: 'H&M', price: 0.40, category: 'Shopping' },
    { id: 'uniqlo', name: 'Uniqlo', price: 0.45, category: 'Shopping' },
    { id: 'sephora', name: 'Sephora', price: 0.50, category: 'Shopping' },
    { id: 'ulta', name: 'Ulta', price: 0.50, category: 'Shopping' },
    { id: 'macys', name: 'Macys', price: 0.50, category: 'Shopping' },
    { id: 'kohls', name: 'Kohls', price: 0.45, category: 'Shopping' },
    { id: 'nordstrom', name: 'Nordstrom', price: 0.55, category: 'Shopping' },
    { id: 'sams_club', name: 'Sams Club', price: 0.50, category: 'Shopping' },

    // --- Gaming (60+) ---
    { id: 'steam', name: 'Steam', price: 0.57, category: 'Gaming' },
    { id: 'g2a', name: 'G2A', price: 0.57, category: 'Gaming' },
    { id: 'eneba', name: 'Eneba', price: 0.57, category: 'Gaming' },
    { id: 'cdkeys', name: 'CDKeys', price: 0.35, category: 'Gaming' },
    { id: 'gamestop', name: 'GameStop', price: 0.40, category: 'Gaming' },
    { id: 'gamefly', name: 'GameFly', price: 0.40, category: 'Gaming' },

    // --- Food & Delivery (50+) ---
    { id: 'ubereats', name: 'Uber Eats', price: 0.50, category: 'Food' },
    { id: 'doordash', name: 'DoorDash', price: 0.50, category: 'Food' },
    { id: 'grubhub', name: 'Grubhub', price: 0.50, category: 'Food' },
    { id: 'postmates', name: 'Postmates', price: 0.50, category: 'Food' },
    { id: 'instacart', name: 'Instacart', price: 0.55, category: 'Food' },
    { id: 'gopuff', name: 'Gopuff', price: 0.45, category: 'Food' },
    { id: 'seamless', name: 'Seamless', price: 0.50, category: 'Food' },
    { id: 'caviar', name: 'Caviar', price: 0.55, category: 'Food' },
    { id: 'delivery_com', name: 'delivery.com', price: 0.45, category: 'Food' },
    { id: 'chowbus', name: 'Chowbus', price: 0.45, category: 'Food' },
    { id: 'fantuan', name: 'Fantuan', price: 0.45, category: 'Food' },
    { id: 'hungry_panda', name: 'HungryPanda', price: 0.45, category: 'Food' },
    { id: 'ricepo', name: 'Ricepo', price: 0.45, category: 'Food' },
    { id: 'skip_dishes', name: 'SkipTheDishes', price: 0.50, category: 'Food' },
    { id: 'just_eat', name: 'Just Eat', price: 0.50, category: 'Food' },
    { id: 'deliveroo', name: 'Deliveroo', price: 0.50, category: 'Food' },
    { id: 'glovo', name: 'Glovo', price: 0.45, category: 'Food' },
    { id: 'wolt', name: 'Wolt', price: 0.50, category: 'Food' },
    { id: 'bolt_food', name: 'Bolt Food', price: 0.45, category: 'Food' },
    { id: 'foodpanda', name: 'Foodpanda', price: 0.45, category: 'Food' },
    { id: 'swiggy', name: 'Swiggy', price: 0.40, category: 'Food' },
    { id: 'zomato', name: 'Zomato', price: 0.40, category: 'Food' },
    { id: 'grab_food', name: 'GrabFood', price: 0.45, category: 'Food' },
    { id: 'gojek', name: 'Gojek', price: 0.45, category: 'Food' },
    { id: 'rappi', name: 'Rappi', price: 0.45, category: 'Food' },
    { id: 'ifood', name: 'iFood', price: 0.45, category: 'Food' },
    { id: 'talabat', name: 'Talabat', price: 0.50, category: 'Food' },
    { id: 'jahez', name: 'Jahez', price: 0.50, category: 'Food' },
    { id: 'hungerstation', name: 'HungerStation', price: 0.50, category: 'Food' },
    { id: 'mcdonalds', name: 'McDonalds', price: 0.40, category: 'Food' },
    { id: 'starbucks', name: 'Starbucks', price: 0.45, category: 'Food' },
    { id: 'dunkin', name: 'Dunkin', price: 0.40, category: 'Food' },
    { id: 'bk', name: 'Burger King', price: 0.40, category: 'Food' },
    { id: 'kfc', name: 'KFC', price: 0.40, category: 'Food' },
    { id: 'subway', name: 'Subway', price: 0.40, category: 'Food' },
    { id: 'dominos', name: 'Dominos', price: 0.40, category: 'Food' },
    { id: 'pizza_hut', name: 'Pizza Hut', price: 0.40, category: 'Food' },
    { id: 'papa_johns', name: 'Papa Johns', price: 0.40, category: 'Food' },
    { id: 'chipotle', name: 'Chipotle', price: 0.45, category: 'Food' },
    { id: 'taco_bell', name: 'Taco Bell', price: 0.40, category: 'Food' },
    { id: 'wendys', name: 'Wendys', price: 0.40, category: 'Food' },
    { id: 'chick_fil_a', name: 'Chick-fil-A', price: 0.45, category: 'Food' },
    { id: 'panera', name: 'Panera', price: 0.45, category: 'Food' },

    // --- Travel & Transport (50+) ---
    { id: 'uber', name: 'Uber', price: 0.55, category: 'Transport' },
    { id: 'lyft', name: 'Lyft', price: 0.55, category: 'Transport' },
    { id: 'bolt', name: 'Bolt', price: 0.50, category: 'Transport' },
    { id: 'grab', name: 'Grab', price: 0.50, category: 'Transport' },
    { id: 'careem', name: 'Careem', price: 0.50, category: 'Transport' },
    { id: 'airbnb', name: 'Airbnb', price: 0.60, category: 'Travel' },
    { id: 'booking', name: 'Booking.com', price: 0.55, category: 'Travel' },
    { id: 'expedia', name: 'Expedia', price: 0.55, category: 'Travel' },
    { id: 'agoda', name: 'Agoda', price: 0.50, category: 'Travel' },
    { id: 'hotels_com', name: 'Hotels.com', price: 0.55, category: 'Travel' },
    { id: 'trip_com', name: 'Trip.com', price: 0.55, category: 'Travel' },
    { id: 'trivago', name: 'Trivago', price: 0.50, category: 'Travel' },
    { id: 'kayak', name: 'Kayak', price: 0.50, category: 'Travel' },
    { id: 'skyscanner', name: 'Skyscanner', price: 0.50, category: 'Travel' },
    { id: 'vrbo', name: 'Vrbo', price: 0.60, category: 'Travel' },
    { id: 'couchsurfing', name: 'Couchsurfing', price: 0.40, category: 'Travel' },
    { id: 'hostelworld', name: 'Hostelworld', price: 0.45, category: 'Travel' },
    { id: 'hopper', name: 'Hopper', price: 0.50, category: 'Travel' },
    { id: 'priceline', name: 'Priceline', price: 0.55, category: 'Travel' },
    { id: 'orbitz', name: 'Orbitz', price: 0.55, category: 'Travel' },
    { id: 'travelocity', name: 'Travelocity', price: 0.55, category: 'Travel' },
    { id: 'delta', name: 'Delta Airlines', price: 0.60, category: 'Travel' },
    { id: 'united', name: 'United Airlines', price: 0.60, category: 'Travel' },
    { id: 'american', name: 'American Airlines', price: 0.60, category: 'Travel' },
    { id: 'southwest', name: 'Southwest Airlines', price: 0.60, category: 'Travel' },
    { id: 'ryanair', name: 'Ryanair', price: 0.50, category: 'Travel' },
    { id: 'easyjet', name: 'easyJet', price: 0.50, category: 'Travel' },
    { id: 'wizz', name: 'Wizz Air', price: 0.50, category: 'Travel' },
    { id: 'lufthansa', name: 'Lufthansa', price: 0.60, category: 'Travel' },
    { id: 'emirates', name: 'Emirates', price: 0.65, category: 'Travel' },
    { id: 'qatar', name: 'Qatar Airways', price: 0.65, category: 'Travel' },
    { id: 'hertz', name: 'Hertz', price: 0.55, category: 'Travel' },
    { id: 'avis', name: 'Avis', price: 0.55, category: 'Travel' },
    { id: 'enterprise', name: 'Enterprise', price: 0.55, category: 'Travel' },
    { id: 'sixt', name: 'Sixt', price: 0.55, category: 'Travel' },
    { id: 'turo', name: 'Turo', price: 0.60, category: 'Travel' },
    { id: 'zipcar', name: 'Zipcar', price: 0.55, category: 'Travel' },
    { id: 'blablacar', name: 'BlaBlaCar', price: 0.50, category: 'Travel' },
    { id: 'lime', name: 'Lime', price: 0.35, category: 'Transport' },
    { id: 'bird', name: 'Bird', price: 0.35, category: 'Transport' },

    // --- Services & Surveys (60+) ---
    { id: 'swagbucks', name: 'Swagbucks', price: 0.40, category: 'Surveys' },
    { id: 'inboxdollars', name: 'InboxDollars', price: 0.40, category: 'Surveys' },
    { id: 'survey_junkie', name: 'Survey Junkie', price: 0.40, category: 'Surveys' },
    { id: 'pinecone_research', name: 'Pinecone Research', price: 0.50, category: 'Surveys' },
    { id: 'vindale_research', name: 'Vindale Research', price: 0.45, category: 'Surveys' },
    { id: 'mypoints', name: 'MyPoints', price: 0.40, category: 'Surveys' },
    { id: 'toluna', name: 'Toluna', price: 0.40, category: 'Surveys' },
    { id: 'prize_rebel', name: 'PrizeRebel', price: 0.40, category: 'Surveys' },
    { id: 'opinion_outpost', name: 'Opinion Outpost', price: 0.45, category: 'Surveys' },
    { id: 'ipsos', name: 'Ipsos i-Say', price: 0.45, category: 'Surveys' },
    { id: 'life_points', name: 'LifePoints', price: 0.40, category: 'Surveys' },
    { id: 'branded_surveys', name: 'Branded Surveys', price: 0.40, category: 'Surveys' },
    { id: 'oneopinion', name: 'OneOpinion', price: 0.45, category: 'Surveys' },
    { id: 'harris_poll', name: 'Harris Poll', price: 0.50, category: 'Surveys' },
    { id: 'valued_opinions', name: 'Valued Opinions', price: 0.45, category: 'Surveys' },
    { id: 'zoom_bucks', name: 'ZoomBucks', price: 0.40, category: 'Surveys' },
    { id: 'grabpoints', name: 'GrabPoints', price: 0.40, category: 'Surveys' },
    { id: 'featurepoints', name: 'FeaturePoints', price: 0.40, category: 'Surveys' },
    { id: 'mistplay', name: 'Mistplay', price: 0.45, category: 'Surveys' },
    { id: 'fetch_rewards', name: 'Fetch Rewards', price: 0.45, category: 'Surveys' },
    { id: 'ibotta', name: 'Ibotta', price: 0.45, category: 'Surveys' },
    { id: 'rakuten_survey', name: 'Rakuten', price: 0.45, category: 'Surveys' },
    { id: 'honey', name: 'Honey', price: 0.40, category: 'Surveys' },
    { id: 'dosh', name: 'Dosh', price: 0.45, category: 'Surveys' },
    { id: 'drop', name: 'Drop', price: 0.45, category: 'Surveys' },
    { id: 'shopkick', name: 'Shopkick', price: 0.40, category: 'Surveys' },
    { id: 'receipt_hog', name: 'Receipt Hog', price: 0.40, category: 'Surveys' },
    { id: 'upwork', name: 'Upwork', price: 0.50, category: 'Work' },
    { id: 'fiverr', name: 'Fiverr', price: 0.45, category: 'Work' },
    { id: 'freelancer', name: 'Freelancer', price: 0.45, category: 'Work' },
    { id: 'guru', name: 'Guru', price: 0.45, category: 'Work' },
    { id: 'peopleperhour', name: 'PeoplePerHour', price: 0.45, category: 'Work' },
    { id: 'taskrabbit', name: 'TaskRabbit', price: 0.50, category: 'Work' },
    { id: 'thumbtack', name: 'Thumbtack', price: 0.50, category: 'Work' },
    { id: 'handy', name: 'Handy', price: 0.50, category: 'Work' },
    { id: 'rover', name: 'Rover', price: 0.50, category: 'Work' },
    { id: 'wag', name: 'Wag', price: 0.50, category: 'Work' },

    // --- Tech, AI & Streaming (50+) ---
    { id: 'google', name: 'Google', price: 0.85, category: 'Tech' },
    { id: 'microsoft', name: 'Microsoft', price: 0.60, category: 'Tech' },
    { id: 'apple', name: 'Apple', price: 0.60, category: 'Tech' },
    { id: 'yahoo', name: 'Yahoo', price: 0.60, category: 'Tech' },
    { id: 'aol', name: 'AOL', price: 0.60, category: 'Tech' },
    { id: 'openai', name: 'OpenAI', price: 0.60, category: 'AI' },
    { id: 'chatgpt', name: 'ChatGPT', price: 0.60, category: 'AI' },
    { id: 'midjourney', name: 'Midjourney', price: 0.55, category: 'AI' },
    { id: 'claude', name: 'Claude (Anthropic)', price: 0.55, category: 'AI' },
    { id: 'stability', name: 'Stability AI', price: 0.55, category: 'AI' },
    { id: 'jasper', name: 'Jasper', price: 0.55, category: 'AI' },
    { id: 'copy_ai', name: 'Copy.ai', price: 0.55, category: 'AI' },
    { id: 'huggingface', name: 'Hugging Face', price: 0.55, category: 'AI' },
    { id: 'replicate', name: 'Replicate', price: 0.55, category: 'AI' },
    { id: 'netflix', name: 'Netflix', price: 0.60, category: 'Streaming' },
    { id: 'disney_plus', name: 'Disney+', price: 0.60, category: 'Streaming' },
    { id: 'hulu', name: 'Hulu', price: 0.60, category: 'Streaming' },
    { id: 'hbo_max', name: 'HBO Max', price: 0.60, category: 'Streaming' },
    { id: 'prime_video', name: 'Prime Video', price: 0.60, category: 'Streaming' },
    { id: 'peacock', name: 'Peacock', price: 0.60, category: 'Streaming' },
    { id: 'paramount_plus', name: 'Paramount+', price: 0.60, category: 'Streaming' },
    { id: 'apple_tv', name: 'Apple TV+', price: 0.60, category: 'Streaming' },
    { id: 'youtube', name: 'YouTube', price: 0.60, category: 'Streaming' },
    { id: 'spotify', name: 'Spotify', price: 0.60, category: 'Streaming' },
    { id: 'apple_music', name: 'Apple Music', price: 0.60, category: 'Streaming' },
    { id: 'tidal', name: 'Tidal', price: 0.60, category: 'Streaming' },
    { id: 'deezer', name: 'Deezer', price: 0.60, category: 'Streaming' },
    { id: 'soundcloud', name: 'SoundCloud', price: 0.60, category: 'Streaming' },
    { id: 'pandora', name: 'Pandora', price: 0.60, category: 'Streaming' },
    { id: 'audiomack', name: 'Audiomack', price: 0.60, category: 'Streaming' },
    { id: 'roku', name: 'Roku', price: 0.60, category: 'Streaming' },
    { id: 'plex', name: 'Plex', price: 0.60, category: 'Streaming' },
    { id: 'tubi', name: 'Tubi', price: 0.60, category: 'Streaming' },
    { id: 'pluto_tv', name: 'Pluto TV', price: 0.60, category: 'Streaming' },
    { id: 'sling', name: 'Sling TV', price: 0.60, category: 'Streaming' },
    { id: 'fubo', name: 'FuboTV', price: 0.60, category: 'Streaming' },
    { id: 'dazn', name: 'DAZN', price: 0.60, category: 'Streaming' },
    { id: 'espn', name: 'ESPN+', price: 0.60, category: 'Streaming' },

    // --- Events & Tickets (New) ---
    { id: 'ticketmaster', name: 'Ticketmaster', price: 0.60, category: 'Events' },
    { id: 'stubhub', name: 'StubHub', price: 0.60, category: 'Events' },
    { id: 'vividseats', name: 'Vivid Seats', price: 0.60, category: 'Events' },
    { id: 'seatgeek', name: 'SeatGeek', price: 0.60, category: 'Events' },
    { id: 'axs', name: 'AXS', price: 0.60, category: 'Events' },
    { id: 'eventbrite', name: 'Eventbrite', price: 0.55, category: 'Events' },

    // --- More Gaming ---
    { id: 'blizzard', name: 'Blizzard (Battle.net)', price: 0.50, category: 'Gaming' },
    { id: 'riot', name: 'Riot Games', price: 0.50, category: 'Gaming' },
    { id: 'epic_games', name: 'Epic Games', price: 0.50, category: 'Gaming' },
    { id: 'roblox', name: 'Roblox', price: 0.45, category: 'Gaming' },
    { id: 'twitch_prime', name: 'Twitch Prime', price: 0.50, category: 'Gaming' },
];
